// Code generated by goctl. DO NOT EDIT.
package types

type OrderReq struct {
	Id string `path:"id"`
}

type OrderReply struct {
	Id   string `json:"id" , validate:"required"`
	Name string `json:"name", validate:"required"`
}

type DownloadRequest struct {
	File string `path:"file"`
}
